
- name: "update timezone"
  timezone:
    name: "Asia/Tokyo"

- name: "update locale"
  tags: "locale"
  shell: "localectl set-locale LANG=en_US.UTF-8"

- name: "update /etc/selinux/config"
  tags: "selinux"
  selinux:
    state: "disabled"

- name: "disable firewalld"
  systemd: 
    name: "firewalld"
    enabled: "no"
    state: "stopped"

