
- name: Check DB Cluster
  stat:
    path: "{{ user['directory_pgdata'] }}13/data/postgresql.conf"
  register: conf_pgdata

- name: Create DB Cluster
  become: yes
  become_user: "{{ user['pg_owner'] }}"
  become_method: su
  shell: /usr/pgsql-13/bin/initdb -E UTF8 --locale=C
  when: conf_pgdata.stat.exists == false

  

- name: 資材コピー
  copy:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    owner: postgres
    group: postgres
    mode: 0600 
  with_items:
    - { src: "/vagrant_data/pgpool.conf", dest: "/etc/pgpool-II/pgpool.conf" }
    - { src: "/vagrant_data/pool_hba.conf", dest: "/etc/pgpool-II/pool_hba.conf" }
    - { src: "/vagrant_data/pool_passwd", dest: "/etc/pgpool-II/pool_passwd"}
    - { src: "/vagrant_data/pgpass", dest: "/var/lib/pgsql/.pgpass"}
    - { src: "/vagrant_data/pcppass", dest: "/var/lib/pgsql/.pcppass"}
    - { src: "/vagrant_data/pgpoolkey", dest: "/var/lib/pgsql/.pgpoolkey" }
    - { src: "/vagrant_data/pcp.conf", dest: "/etc/pgpool-II/pcp.conf" }

- name: 資材コピー
  copy:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    owner: postgres
    group: postgres
    mode: 0755
  with_items:
    - { src: "/vagrant_data/escalation.sh", dest: "/etc/pgpool-II/escalation.sh"}
    - { src: "/vagrant_data/recovery_1st_stage",dest: "/var/lib/pgsql/13/data/recovery_1st_stage"}
    - { src: "/vagrant_data/pgpool_remote_start",dest: "/var/lib/pgsql/13/data/pgpool_remote_start"}
    - { src: "/vagrant_data/pgpool", dest: "/etc/sysconfig/pgpool"}
    - { src: "/vagrant_data/failover.sh", dest: "/etc/pgpool-II/failover.sh"}
    - { src: "/vagrant_data/follow_primary.sh", dest: "/etc/pgpool-II/follow_primary.sh"}


- name: file test
  file:
    path: /etc/pgpool-II/pgpool_node_id
    state: touch
    owner: "{{ user['pg_owner'] }}"
    group: "{{ user['pg_group'] }}"
    mode: 0644

- name: nodeid追加
  lineinfile:
    path: /etc/pgpool-II/pgpool_node_id
    line: "{{ node_id }}"



- name: restart service
  systemd:
    name: "{{ item }}"
    state: restarted
    daemon_reload: yes
    enabled: yes
  with_items:
    - pgpool.service
    - postgresql-13.service