# - name: Create schema
#   become_user: postgres
#   postgresql_schema:
#     name: "{{ item.name }}"
#     owner: "{{ item.owner|default('postgres') }}"
#     port: "{{ postgresql_port }}"
#   with_items: "{{ postgresql_schemas }}"

# - name: Create database
#   become_user: postgres
#   postgresql_db:
#     name: "{{ item.name }}"
#     template: "{{ item.template|default('template1') }}"
#     lc_collate: "{{ item.lc_collate|default('C') }}"
#     lc_ctype: "{{ item.lc_ctype|default('C') }}"
#     port: "{{ postgresql_port }}"
#   with_items: "{{ postgresql_databases }}"



# - name: initdb
#   shell: /usr/pgsql-13/bin/initdb -E UTF8 --locale=C -A scram-sha-256 -W
#   become: yes
#   become_user: postgres
#   when: not dbcluster.stat.exists

- name: Create PostgreSQL database
  postgresql_db:
    name: postgres
    owner: postgres
    encoding: 'UTF-8'
    lc_collate: 'ja_JP.UTF-8'
    lc_ctype: 'ja_JP.UTF-8'
    template: 'template0'
    login_user: postgres
    login_password: "{{ user['db_pass'] }}"
  notify: Restart postgresql-13


- name: Create PostgreSQL user
  postgresql_user:
    name: postgres
    password: "{{ user['db_pass'] }}"
    login_user: postgres
    login_password: "{{ user['db_pass'] }}"
  notify: Restart postgresql-13




# - name: 資材コピー
#   copy:
#     src: "{{item.src}}"
#     dest: "{{item.dest}}"
#     owner: postgres
#     group: postgres
#     mode: 0600 
#   with_items:
#     - { src: "/vagrant_data/pgpool.conf", dest: "/etc/pgpool-II/pgpool.conf" }
#     - { src: "/vagrant_data/pool_hba.conf", dest: "/etc/pgpool-II/pool_hba.conf" }
#     - { src: "/vagrant_data/pool_passwd", dest: "/etc/pgpool-II/pool_passwd"}
#     - { src: "/vagrant_data/.pgpass", dest: "/var/lib/pgsql/.pgpass"}
#     - { src: "/vagrant_data/.pcppass", dest: "/home/postgres/.pcppass"}
#     - { src: "/vagrant_data/.pgpoolkey", dest: "/home/postgres/.pgpoolkey" }
#     - { src: "/vagrant_data/pcp.conf", dest: "/etc/pgpool-II/pcp.conf" }

# - name: 資材コピー
#   copy:
#     src: "{{item.src}}"
#     dest: "{{item.dest}}"
#     owner: postgres
#     group: postgres
#     mode: 0755
#   with_items:
#     - { src: "/vagrant_data/escalation.sh", dest: "/etc/pgpool-II/escalation.sh"}
#     - { src: "/vagrant_data/recovery_1st_stage",dest: "/var/lib/pgsql/13/data/recovery_1st_stage"}
#     - { src: "/vagrant_data/pgpool_remote_start",dest: "/var/lib/pgsql/13/data/pgpool_remote_start"}
#     - { src: "/vagrant_data/pgpool", dest: "/etc/sysconfig/pgpool"}
#     - { src: "/vagrant_data/failover.sh", dest: "/etc/pgpool-II/failover.sh"}
#     - { src: "/vagrant_data/follow_primary.sh", dest: "/etc/pgpool-II/follow_primary.sh"}


# - name: pgpool_node_id
#   shell: echo "0" > /etc/pgpool-II/pgpool_node_id
#   when: inventory_hostname == 'server1'

# - name: pgpool_node_id
#   shell: echo "1" > /etc/pgpool-II/pgpool_node_id
#   when: inventory_hostname == 'server2'

# - name: pgpool_node_id
#   shell: echo "2" > /etc/pgpool-II/pgpool_node_id
#   when: inventory_hostname == 'server3'



- name: restart service
  systemd:
    name: "{{ item }}"
    state: restarted
    daemon_reload: yes
    enabled: yes
  with_items:
    - pgpool.service
    # - postgresql-13.service