
- name: hosts追加
  lineinfile:
    path: /etc/hosts
    line: "{{item.line}}"
  with_items:
    - { line: '192.168.137.101 server1' }
    - { line: '192.168.137.102 server2' }
    - { line: '192.168.137.103 server3' }        

