
- name: Group Add
  group:
    name: "{{ user['pg_group'] }}"

- name: User Add
  user:
    name: "{{ user['pg_owner'] }}"
    shell: "/bin/bash"
    group: "{{ user['pg_group'] }}"
    password: "{{ 'postgres' | password_hash('sha512') }}"
    generate_ssh_key: "yes"
    ssh_key_bits: "2048"
    ssh_key_file: .ssh/{{ user['keyname'] }}
    home: "/var/lib/pgsql/"
  register: key_context


